Repository CrewMates-Open-Source/EduHelp, pull requests merged in 2021-04, with the labels that each got.

#44 Speech to text module #36
  Jupyter_Notebooks/Speech_To_Text.ipynb
  Jupyter_Notebooks/transcription.txt
  requirements.txt
Labels: gssoc21, level3

#51 update readme.md
  README.md
Labels: gssoc21, level1

#61 summarizer code added
  Jupyter_Notebooks/Extraction_Based_Summarizer#38.ipynb
Labels: gssoc21, level3

#66 Back to top button added
  index.html
  website/style.css
Labels: gssoc21, level2

#70 new Contact us section
  contact.html
  index.html
  website/style.css
Labels: gssoc21, level3

#72 [Gssoc'21]background color of Footer changed
  index.html
  website/style.css
Labels: gssoc21, level1

#79 Local_conversion_Of_speech_to_text
  Jupyter_Notebooks/local_conversion_of_speech_to_text.ipynb
  requirements.txt
Labels: gssoc21, level3

#82 Added the Preloader
  index.html
  website/image/preloaderimg.gif
Labels: gssoc21, level2

#85 Added the Wave to the website
  index.html
  website/style.css
Labels: gssoc21, level3

#88 Improved the you tube video section
  index.html
  website/style.css
Labels: gssoc21, level2

#89 Improved About section
  index.html
  website/style.css
Labels: gssoc21, level2
